Fix #7
NREL-Sienna/PowerAnalytics.jl pull request #17
Opened 2023-10-27 23:36 UTC by GabrielKS

This fixes PowerAnalytics bug #7.
---
 - Delete the offending `.DS_Store`
 - Import a good `.gitignore` from `PowerSystems`
 - Import formatter structure from `PowerSystems` as well
 - Run the formatter
 - Clean up the `docs` directory

I have been unable to reproduce the issue with the documentation build; leaving this as a draft for now until I can confirm that that is no longer an issue.

2023-11-06 21:16 UTC, GabrielKS commented
@jd-lara can you check if the "Documentation is failing" issue you reported at https://github.com/NREL-Sienna/PowerAnalytics.jl/issues/7 is still present? It looks fine to me.

2023-11-06 22:21 UTC, jd-lara commented on scripts/generate_config_file.py
This file isn't needed in PowerAnalytics. Please remove

2023-11-06 22:22 UTC, jd-lara commented on scripts/generate_validation_config_file.py
This file should also be removed

2023-11-06 22:22 UTC, jd-lara requested changes
Remove not needed files

2023-11-07 19:18 UTC, GabrielKS commented on scripts/generate_config_file.py
Done

2023-11-07 19:18 UTC, GabrielKS commented on scripts/generate_validation_config_file.py
Done

2023-11-09 01:59 UTC, jd-lara approved these changes

2023-11-09 01:59 UTC, merged