Make PowerAnalytics work with PSY4
NREL-Sienna/PowerAnalytics.jl pull request #22
Opened 2024-06-05 17:08 UTC by GabrielKS

Draft, the simulation that generates test data is still failing. I'm using the following patches to get this far:

- In `HydroPowerSimulations.jl/src/hydro_generation.jl` (this one should probably be committed):
```
-PSI.proportional_cost(cost::PSY.HydroGenerationCost , ::HydroEnergySurplusVariable, ::PSY.HydroGen, ::AbstractHydroReservoirFormulation)=PSY.get_energy_surplus_cost(cost)
-PSI.proportional_cost(cost::PSY.HydroGenerationCost , ::HydroEnergyShortageVariable, ::PSY.HydroGen, ::AbstractHydroReservoirFormulation)=PSY.get_energy_shortage_cost(cost)
+PSI.proportional_cost(cost::PSY.StorageCost , ::HydroEnergySurplusVariable, ::PSY.HydroGen, ::AbstractHydroReservoirFormulation)=PSY.get_energy_surplus_cost(cost)
+PSI.proportional_cost(cost::PSY.StorageCost , ::HydroEnergyShortageVariable, ::PSY.HydroGen, ::AbstractHydroReservoirFormulation)=PSY.get_energy_shortage_cost(cost)
```
- In `PowerSystems.jl/src/models/cost_functions/StorageCost.jl` (this one is just a kludge until something gets updated in PSI):
```
+get_variable(value::StorageCost) = get_discharge_variable_cost(value)
```

2024-06-07 00:03 UTC, GabrielKS commented
The simulation and all old PA tests pass now, at the cost of removing simulation of hydro. The two patches above are still required.

2024-06-10 16:15 UTC, jd-lara commented on src/get_data.jl
> +                len = (horizon isa Dates.Period) ? Int64(horizon / resolution) : horizon
We have methods in PSY to handle this

2024-06-10 16:17 UTC, jd-lara requested changes
Update the time series handling using PSY4 correctly.

2024-06-10 16:17 UTC, GabrielKS commented on src/get_data.jl
> +                len = (horizon isa Dates.Period) ? Int64(horizon / resolution) : horizon
Is there a way to `get_time_series_values` passing in a `Period`?

2024-06-11 17:07 UTC, GabrielKS commented
@daniel-thom is there a way to get a subset of a time series using a horizon `Period` as @jd-lara is requesting? I couldn't find one.

2024-06-11 18:56 UTC, daniel-thom commented
> @daniel-thom is there a way to get a subset of a time series using a horizon `Period` as @jd-lara is requesting? I couldn't find one.

Nope, we missed this one. You can only pass horizon_count as `len`. It could be fixed relatively easily.

2024-06-25 17:13 UTC, merged