Total PowerAnalytics Redesign: `ComponentSelector`s and `Metric`s
NREL-Sienna/PowerAnalytics.jl pull request #24
Opened 2024-09-30 07:15 UTC by GabrielKS

See https://github.nrel.gov/gkonars/PowerAnalytics-demos/blob/main/new_pa_pr_demo.ipynb for a full demo. Depends on https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/342 and https://github.com/NREL-Sienna/PowerSystems.jl/pull/1197.

2024-10-08 21:00 UTC, jd-lara commented on src/metrics.jl
> +
```suggestion
function is_available_for_analytics(comp::T)
if hasmethod(PSY.get_available, Tuple{T})
        return PSY.get_available(comp)
 else
 return true
    end
    

```

2024-10-08 21:05 UTC, GabrielKS commented on src/metrics.jl
> +
My impression was that `hasmethod` isn't really supposed to be used in production code like this (see e.g. [here](https://github.com/JuliaLang/julia/issues/45526#issuecomment-1142728643)) but happy to switch if the consensus is it's less bad than the try/catch

2024-10-08 22:50 UTC, daniel-thom commented on src/metrics.jl
> +
It's an exported function with proper docstrings! I'm not sure about that comment. Anyway, we could implement `get_available(x::Component) = true`. I'll defer to @jd-lara if that is a reasonable default. It has the same outcome here.

2024-10-08 23:02 UTC, daniel-thom commented on src/metrics.jl
> +
While hasmethod certainly isn't ideal, it is faster than try/catch: https://discourse.julialang.org/t/performance-of-hasmethod-vs-try-catch-on-methoderror/99827.

A default get_available is obviously still better.

2024-10-09 14:24 UTC, daniel-thom requested changes

2024-10-09 14:24 UTC, daniel-thom commented on test/test_input.jl
> +# TODO is there a better way?
`compare_values`?

2024-10-09 14:24 UTC, daniel-thom commented on test/test_input.jl
> +# Reimplements Base.Filesystem.cptree since that isn't exported
It seems crazy that Julia does not provide a way to do this. Since this is just a test, I would have just called the internal function, but am not asking for a change.

2024-10-09 14:24 UTC, daniel-thom commented on test/test_metrics.jl
> +comp_results = Dict()  # Will be populated later
Does this introduce risks of tests colliding with each other?

2024-10-09 14:24 UTC, daniel-thom commented on test/setuptests.jl
> +!isdir(TEST_OUTPUTS) && mkdir(TEST_OUTPUTS)
Can you use a tmpdir for all outputs?

2024-10-09 14:24 UTC, daniel-thom commented on test/test_builtin_metrics.jl
> +# For now we are mostly just testing that all the metrics can be called without error,
Is this still correct? I see plenty of places where you are checking the values returned by functions like aggregate_time. Are there any important functions where you aren't validating the returned values?

2024-10-09 17:03 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +import Base: @kwdef
Not in older minor versions we commit to supporting (see https://github.com/NREL-Sienna/InfrastructureSystems.jl/pull/390)

2024-10-09 17:13 UTC, daniel-thom commented on src/PowerAnalytics.jl
> +import Base: @kwdef
I see. @jd-lara Is it time to force users to upgrade? 1.11 is out. If people haven't upgraded to at least 1.9, they probably should.

2024-10-09 18:05 UTC, GabrielKS commented on src/metrics.jl
> +
Agree that the best option for this use case is to define `get_available` on all `Component`s — @jd-lara does that work for you?

2024-10-09 18:06 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +# Old PowerAnalytics
I'm trying to maintain a strict separation between the two interfaces until we decide what to do with the old one (e.g., should it be deprecated once PowerGraphics no longer depends on it)?

2024-10-09 18:10 UTC, daniel-thom commented on src/PowerAnalytics.jl
> +# Old PowerAnalytics
Can this be a 1.0 vs 2.0 kinda thing? Basically, do we need to maintain support for the old methods in the new version if those users can continue to use the old version?

2024-10-09 18:18 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +# Old PowerAnalytics
One issue is that the _current_ latest version of PowerGraphics depends on old PowerAnalytics and I don't want to keep PowerGraphics users from using new PowerAnalytics. I'm thinking something like this:

1. Release new PA, keep old PA as is
2. Develop a user base on new PA, fix some bugs
3. Deprecate old PA (i.e., throw warnings) but keep it so PG can use it
4. Revamp PG to only depend on new PA (I would be interested in supervising an intern to do this)
5. Remove old PA

but not committed to that, open to discussion.

2024-10-09 18:20 UTC, GabrielKS commented on src/PowerAnalytics.jl
>  greet() = print("Hello World!")
Yeah, will do. Surprised that this is the only package of ours that still has it

2024-10-09 18:21 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    gen_type = getproperty(PowerSystems, Symbol(get(category_spec, "gentype", Component)))
You're right, I should make this more flexible somehow.

2024-10-09 18:21 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    isnothing(pm) || (pm = PowerSystems.parse_enum_mapping(PowerSystems.PrimeMovers, pm))
Will do, I don't mind the convention

2024-10-09 18:22 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +all_loads::ComponentSelector = make_selector(PSY.ElectricLoad)
Will do

2024-10-09 18:23 UTC, GabrielKS commented on src/input_utils.jl
> +const EntryType = Union{
That'd be a PR to PowerSimulations, I'd support but maybe it can be done as an implementation detail later?

2024-10-09 18:26 UTC, GabrielKS commented on src/metrics.jl
> +# TODO there is probably a more principled way of structuring this Metric type hierarchy -- maybe parameterization?
I would like to change this as soon as possible but think it's probably best to prioritize getting this out into the world first. I can keep track of it elsewhere though.

2024-10-09 18:26 UTC, GabrielKS commented on src/metrics.jl
> +ComputationTuple = Tuple{<:T, Any, Any} where {T <: Union{TimedMetric, TimelessMetric}}
Will do

2024-10-09 18:27 UTC, GabrielKS commented on test/test_input.jl
> +# Reimplements Base.Filesystem.cptree since that isn't exported
Oh yeah, this is the basic filesystem function that Julia doesn't provide that I was trying to think of in a recent discussion of ours

2024-10-09 18:29 UTC, GabrielKS commented on test/test_metrics.jl
> +comp_results = Dict()  # Will be populated later
It does seem like a kind of bad use of global state, I'll look into changing this

2024-10-09 18:29 UTC, GabrielKS commented on test/setuptests.jl
> +!isdir(TEST_OUTPUTS) && mkdir(TEST_OUTPUTS)
This is roughly what PA had before and it's been useful to cache these results so we don't have to regenerate them every time we run the tests

2024-10-09 18:31 UTC, GabrielKS commented on test/test_builtin_metrics.jl
> +# For now we are mostly just testing that all the metrics can be called without error,
The "infrastructure," including everything in `metrics.jl`, gets tested pretty thoroughly, this comment only applies to the built-in metrics — like, we aren't testing that `calc_active_power` is actually calculating the active power

2024-10-09 18:37 UTC, GabrielKS commented on src/builtin_metrics.jl
> +            set_agg_meta!(result, power)
This is a manifestation of the second major thing I'd like to address in the next version of PA (see our DMs). Certain metrics need to keep track of element-wise weights to be able to aggregate themselves properly, that's what's going on here. Right now the weights get stored as dataframe metadata, which gets the job done but isn't ideal for a number of reasons; I have an idea of how to improve this later in a way that doesn't impact the casual user interface.

2024-10-09 18:38 UTC, GabrielKS commented on src/builtin_metrics.jl
> +function weighted_mean(values, weights)  # Made quite finnicky by the need to broadcast in two dimensions (or am I just new to this?)
I'll look back into this, I'm sure I'll be able to write something better now, being less "new to this" lol

2024-10-09 18:41 UTC, GabrielKS commented on src/builtin_metrics.jl
> +# TODO test all of this
Done enough to remove this comment, will do

2024-10-09 19:50 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    for top_level in in_data |> keys |> collect
Done

2024-10-09 19:54 UTC, GabrielKS commented on src/builtin_metrics.jl
> +            set_agg_meta!(result, power)
Added an issue for this: https://github.com/NREL-Sienna/PowerAnalytics.jl/issues/27

2024-10-09 19:56 UTC, GabrielKS commented on src/input_utils.jl
> +const DATETIME_COL::String = "DateTime"
The docstring or the TODO? If the docstring — this gets exported, shouldn't everything that gets exported have a docstring?

2024-10-09 19:57 UTC, GabrielKS commented on src/metrics.jl
> +# TODO there is probably a more principled way of structuring this Metric type hierarchy -- maybe parameterization?
Moved to https://github.com/NREL-Sienna/PowerAnalytics.jl/issues/25

2024-10-09 19:59 UTC, GabrielKS commented on src/output_utils.jl
> +    agg_fn = nothing)
Is the better formatting to have the close paren unindented on the next line? If so I am not opposed, the formatter just didn't do it for me

2024-10-09 20:09 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    # Use reflection to look up the type corresponding the generator type string (this isn't a security risk, is it?)
Done

2024-10-09 20:09 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    isnothing(pm) || (pm = PowerSystems.parse_enum_mapping(PowerSystems.PrimeMovers, pm))
Done

2024-10-09 20:09 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +all_loads::ComponentSelector = make_selector(PSY.ElectricLoad)
Done

2024-10-09 20:09 UTC, GabrielKS commented on src/builtin_metrics.jl
> +# TODO test all of this
Done

2024-10-09 20:10 UTC, GabrielKS commented on src/metrics.jl
> +ComputationTuple = Tuple{<:T, Any, Any} where {T <: Union{TimedMetric, TimelessMetric}}
done

2024-10-09 20:31 UTC, daniel-thom commented on src/PowerAnalytics.jl
> +# Old PowerAnalytics
Sounds good to me.

2024-10-09 20:35 UTC, daniel-thom commented on src/builtin_component_selectors.jl
> +    gen_type = getproperty(PowerSystems, Symbol(get(category_spec, "gentype", Component)))
The problem is that I don't see how it could ever be solved. I'm guessing that the PSY table data parser does something like this, and that's OK because it's only parsing types that it knows about. Would this function ever because in a situation with custom types? I'm ok with moving forward if we can bound the problem.

2024-10-09 20:40 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    gen_type = getproperty(PowerSystems, Symbol(get(category_spec, "gentype", Component)))
We definitely do something like this to load serialized systems, I think by checking the `Main` namespace — I get errors loading certain Sourabh systems if I haven't done `using StorageSystemsSimulations` — so I'm envisioning something like that. This only gets called on types listed in `generator_mapping.yaml`, but you can have a custom `generator_mapping.yaml` and I can envision Sourabh putting his custom types there.

2024-10-09 20:51 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +# Old PowerAnalytics
-> https://github.com/NREL-Sienna/PowerAnalytics.jl/issues/28

2024-10-09 21:16 UTC, daniel-thom commented on src/builtin_component_selectors.jl
> +    gen_type = getproperty(PowerSystems, Symbol(get(category_spec, "gentype", Component)))
Then that file will have to include the name of the package so that you know what to pass to getproperty. That is a change that could/should be made now.

2024-10-09 21:18 UTC, daniel-thom commented on src/input_utils.jl
> +const DATETIME_COL::String = "DateTime"
Sorry, I just meant that the type annotation should not be needed.
```suggestion
const DATETIME_COL = "DateTime"
```

2024-10-09 21:18 UTC, daniel-thom commented on src/input_utils.jl
> +const EntryType = Union{
Ok.

2024-10-09 21:20 UTC, daniel-thom commented on src/output_utils.jl
> +    agg_fn = nothing)
That's weird. I would have expected it to fix this. I wonder if there is a bug in the formatter.

2024-10-09 21:20 UTC, daniel-thom commented on test/setuptests.jl
> +!isdir(TEST_OUTPUTS) && mkdir(TEST_OUTPUTS)
Ah, it's for caching. Can you add a comment?

2024-10-24 22:15 UTC, GabrielKS commented on src/metrics.jl
> +
Without objection, moving forward with defining
```julia
get_available(::Component) = true
```
in PSY to eliminate this.

2025-01-29 21:14 UTC, GabrielKS commented on src/metrics.jl
> +
Availability is now handled elsewhere; this function has been deleted.

2025-01-29 21:16 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +import Base: @kwdef
`import Base: @kwdef` is now standard in many Sienna packages, so if we want to make this decision we should make it uniformly across the ecosystem.

2025-01-29 21:27 UTC, GabrielKS commented on src/input_utils.jl
> +const EntryType = Union{
-> opened issue at https://github.com/NREL-Sienna/PowerSimulations.jl/issues/1229

2025-01-29 21:39 UTC, GabrielKS commented on src/input_utils.jl
> +const DATETIME_COL::String = "DateTime"
Done

2025-01-29 21:40 UTC, GabrielKS commented on src/output_utils.jl
> +    agg_fn = nothing)
Done manually

2025-01-29 21:41 UTC, GabrielKS commented on test/setuptests.jl
> +!isdir(TEST_OUTPUTS) && mkdir(TEST_OUTPUTS)
Done

2025-01-29 22:08 UTC, jd-lara commented on test/setuptests.jl
> +using GLPK
replace GLPK with HiGHS

2025-01-30 05:37 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    selector_name = join(ifelse.(isnothing.(parse_results), "", string.(parse_results)),
Done:

1. If `prime_mover` and `fuel_category` are both nothing, the name will be just the type name, else if one is nothing that portion reads as `Any`.
2. Now calling `string(nameof(gen_type))`

2025-01-30 06:32 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +    gen_type = getproperty(PowerSystems, Symbol(get(category_spec, "gentype", Component)))
Resolved: new behavior, implemented in the helper function `lookup_gentype`, is to look up the module name if the gentype is a qualified name, else default to `PowerSystems` for convenience/backwards compatibility:
```julia
PA.lookup_gentype("InfrastructureSystems.InfrastructureSystemsComponent") === IS.InfrastructureSystemsComponent
PA.lookup_gentype("Component") === PSY.Component
```

2025-01-30 06:40 UTC, GabrielKS commented on src/builtin_metrics.jl
> +# TODO is this the appropriate place to put a default threshold (and is it the appropriate default)?
@jd-lara thoughts?

2025-01-30 06:51 UTC, jd-lara commented on src/PowerAnalytics.jl
> +import Base: @kwdef
we can brake the LTS support

2025-01-30 06:55 UTC, jd-lara commented on src/builtin_metrics.jl
> +# TODO is this the appropriate place to put a default threshold (and is it the appropriate default)?
`1e-4` at the original `1e-3` it is about 0.1 MW since the values are usually per unit.

2025-01-30 06:56 UTC, jd-lara commented on src/PowerAnalytics.jl
> +export is_col_meta, set_col_meta, set_col_meta!, time_df, time_vec, data_cols, data_df,
agreed on this

2025-01-30 06:57 UTC, jd-lara commented on src/builtin_metrics.jl
> +function weighted_mean(values, weights)  # Made quite finnicky by the need to broadcast in two dimensions (or am I just new to this?)
This issue is still pending here

2025-01-30 07:30 UTC, GabrielKS commented on test/setuptests.jl
> +using GLPK
Done

2025-01-30 07:52 UTC, GabrielKS commented on test/test_metrics.jl
> +comp_results = Dict()  # Will be populated later
Resolved: at the cost of a bit of recomputation, no `@testset` should depend on another anymore

2025-01-30 08:04 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +all_loads::ComponentSelector = make_selector(PSY.ElectricLoad)
Now *actually* done…

2025-01-30 09:05 UTC, GabrielKS commented on src/builtin_metrics.jl
> +function weighted_mean(values, weights)  # Made quite finnicky by the need to broadcast in two dimensions (or am I just new to this?)
Yeah, that was a little crazy. Rewrote a little less crazily.

2025-01-30 09:06 UTC, GabrielKS commented on test/test_input.jl
> +# TODO is there a better way?
Yep, done.

2025-01-30 09:40 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +export is_col_meta, set_col_meta, set_col_meta!, time_df, time_vec, data_cols, data_df,
Done. `time_df` -> `get_time_df` and similar for all similar exported functions

2025-01-30 10:28 UTC, GabrielKS commented on src/builtin_metrics.jl
> +        catch
Done. I think this code predated the new cost functions!

2025-01-30 10:32 UTC, GabrielKS commented on src/output_utils.jl
> +function hcat_timed(vals::DataFrame...)  # TODO incorporate allow_missing
Doesn't `hcat_time_columns` make it sound like it's concatenating the time columns and dropping everything else? Thoughts on `hcat_timed_dfs`?

2025-01-30 11:32 UTC, GabrielKS commented on src/input_utils.jl
> +# TODO test
Now it is!

2025-01-30 11:34 UTC, GabrielKS commented on src/builtin_metrics.jl
> +# TODO is this the appropriate place to put a default threshold (and is it the appropriate default)?
@jd-lara I don't think I understand your comment

2025-01-30 11:35 UTC, GabrielKS commented
@daniel-thom @jd-lara Ready for another review. If my resolutions above satisfy everyone, I think the outstanding items to discuss are:

- What to do about `import Base: @kwdef`. Since this is a thing in lots of different Sienna repos, I propose we handle it uniformly, i.e., not as part of this PR.
- What to choose as a sensible default slack up threshold/whether to do so
- Naming of `hcat_timed`

2025-01-31 14:52 UTC, daniel-thom commented on src/PowerAnalytics.jl
> +import Base: @kwdef
I don't have a sense for how painful this would be for users: we could set the minimum version as the new LTS of 1.10.8 (https://julialang.org/downloads/#long_term_support_release).

2025-01-31 15:12 UTC, daniel-thom approved these changes
LGTM. One minor comment you could consider.

2025-01-31 15:12 UTC, daniel-thom commented on src/output_utils.jl
> +function hcat_timed(vals::DataFrame...)  # TODO incorporate allow_missing
OK

2025-01-31 18:40 UTC, GabrielKS commented on src/builtin_metrics.jl
> +# TODO is this the appropriate place to put a default threshold (and is it the appropriate default)?
Addressed: changed threshold to `1e-4`

2025-01-31 18:42 UTC, GabrielKS commented on src/PowerAnalytics.jl
> +import Base: @kwdef
Okay. I propose we merge this with the import, which will make it consistent with PSY, IS, etc., and then do a bunch of "drop support pre-1.10" PRs to uniformly update things across the ecosystem.

2025-01-31 18:42 UTC, GabrielKS commented on src/output_utils.jl
> +function hcat_timed(vals::DataFrame...)  # TODO incorporate allow_missing
Done: renamed to `hcat_timed_dfs`

2025-01-31 18:42 UTC, GabrielKS commented on src/builtin_component_selectors.jl
> +        length(in_data[top_level]) > 0 && length(subselectors) == 0 && continue
Done

2025-01-31 18:42 UTC, GabrielKS commented on src/builtin_metrics.jl
> +# TODO test
Now they are

2025-02-04 23:30 UTC, jd-lara commented on src/input_utils.jl
> +const EntryType = Union{
This would be abstracted in InfrastructureSystems in the Optimization submodule

2025-02-04 23:32 UTC, jd-lara approved these changes

2025-02-04 23:32 UTC, merged